plugins {
    id 'java'
}

group = 'com.kingbrezz'
version = '1.0.0'

repositories {
    mavenCentral()

    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }

    maven {
        name = 'jitpack'
        url = 'https://jitpack.io'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2-R0.1-SNAPSHOT'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    filteringCharset = 'UTF-8'

    filesMatching('plugin.yml') {
        expand(
            version: project.version
        )
    }
}

jar {
    archiveBaseName = 'DonutShop'
    archiveVersion = project.version

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
