package com.kingbrezz.donutshop;
import org.bukkit.*; import org.bukkit.entity.Player; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta; import java.util.*;
public final class ShopMenu { private ShopMenu(){} public static final class Holder implements InventoryHolder {private final String category; private Inventory inv; Holder(String c){category=c;} void bind(Inventory i){inv=i;} public String category(){return category;} public boolean isMain(){return "__main__".equals(category);} @Override public Inventory getInventory(){return inv;}}
 public static void openMain(DonutShop p,Player player){int size=normalize(p.getConfig().getInt("shop.main-menu.size",27)); Holder h=new Holder("__main__"); Inventory inv=Bukkit.createInventory(h,size,color(p.getConfig().getString("shop.main-menu.title","&8DonutShop"))); h.bind(inv); List<String> ids=p.getConfig().getStringList("shop.main-menu.categories"); List<Integer> slots=p.getConfig().getIntegerList("shop.main-menu.category-slots"); for(int i=0;i<ids.size()&&i<slots.size();i++){ShopCategory c=p.getShopManager().getCategory(ids.get(i));if(c!=null&&slots.get(i)>=0&&slots.get(i)<size)inv.setItem(slots.get(i),icon(c));} player.openInventory(inv);}
 public static void openCategory(DonutShop p,Player player,ShopCategory c){int size=normalize(p.getConfig().getInt("shop.category-menu.size",27)); Holder h=new Holder(c.id());Inventory inv=Bukkit.createInventory(h,size,color(c.name()));h.bind(inv);for(ShopItem item:c.items())if(item.slot()<size)inv.setItem(item.slot(),display(p,item)); ItemStack back=new ItemStack(Material.ARROW); ItemMeta bm=back.getItemMeta(); bm.setDisplayName(color(p.getConfig().getString("shop.category-menu.back-name","&cBack"))); back.setItemMeta(bm); inv.setItem(p.getConfig().getInt("shop.category-menu.back-slot",0),back); player.openInventory(inv);}
 static ItemStack display(DonutShop p,ShopItem item){ItemStack s=new ItemStack(item.material());ItemMeta m=s.getItemMeta();m.setDisplayName(color(item.displayName()));List<String> lore=new ArrayList<>();for(String x:item.lore())lore.add(color(x));lore.add("");lore.add(color(p.getConfig().getString("shop.item-lore.buy","&7Price: &a{price}").replace("{price}",String.format(Locale.US,"%.2f",item.buyPrice()))));lore.add(color(p.getConfig().getString("shop.item-lore.click","&eLeft-click to buy &7| &eShift-click for bulk")));m.setLore(lore);s.setItemMeta(m);return s;}
 private static ItemStack icon(ShopCategory c){ItemStack s=new ItemStack(c.icon());ItemMeta m=s.getItemMeta();m.setDisplayName(color(c.name()));s.setItemMeta(m);return s;}
 private static int normalize(int n){if(n<9)n=9;if(n>54)n=54;return n-n%9;}
 static String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}
}
