package com.kingbrezz.donutshop;

import org.bukkit.*; import org.bukkit.entity.Player; import org.bukkit.event.inventory.ClickType; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta;
import java.util.*; import java.util.regex.*;

public final class ShopEditMenu {
 private static final Map<UUID,Session> sessions=new HashMap<>(); private ShopEditMenu(){}
 public static final class Holder implements InventoryHolder {private final String category;private Inventory inv;Holder(String c){category=c;}void bind(Inventory i){inv=i;}public String category(){return category;}public Inventory getInventory(){return inv;}}
 private static final class Session {final String category; ItemStack selected; Session(String c){category=c;}}
 public static void open(DonutShop p,Player player,ShopCategory c){close(player);int size=normalize(p.getConfig().getInt("shop-edit.size",54));Holder h=new Holder(c.id());Inventory inv=Bukkit.createInventory(h,size,color(p.getConfig().getString("shop-edit.title","&8ShopEdit &7• &f{category}").replace("{category}",c.id())));h.bind(inv);sessions.put(player.getUniqueId(),new Session(c.id()));for(ShopItem i:c.items())if(i.slot()<size)inv.setItem(i.slot(),ShopMenu.display(p,i));inv.setItem(4,help(p));player.openInventory(inv);}
 public static void handlePlayerClick(DonutShop p,Player player,int raw,ClickType click){Session s=sessions.get(player.getUniqueId());if(s==null)return;ItemStack source=player.getInventory().getItem(raw-p.getConfig().getInt("shop-edit.size",54));if(source==null||source.getType().isAir()){p.getLanguageManager().send(player,"messages.shopedit-invalid-item");return;}ItemStack selected=source.clone();selected.setAmount(1);s.selected=selected;p.getLanguageManager().send(player,"messages.shopedit-item-selected");}
 public static void handleTopClick(DonutShop p,Player player,Holder holder,int slot,ClickType click){Session s=sessions.get(player.getUniqueId());if(s==null)return;int size=holder.getInventory().getSize();if(slot==4){p.getLanguageManager().send(player,"messages.shopedit-help");return;}int min=p.getConfig().getInt("shop-edit.allowed-slots.min",9),max=p.getConfig().getInt("shop-edit.allowed-slots.max",44);if(slot<min||slot>max){p.getLanguageManager().send(player,"messages.shopedit-reserved-slot");return;}ShopCategory c=p.getShopManager().getCategory(holder.category());if(c==null)return;
  if(click.isRightClick()&&!click.isShiftClick()){ShopItem old=c.getItemBySlot(slot);if(old!=null){p.getShopManager().removeConfigSection("categories."+c.id()+".items."+old.id());c.removeItem(old.id());p.getLanguageManager().send(player,"messages.shopedit-item-removed");autosave(p);}return;}
  if(s.selected==null){p.getLanguageManager().send(player,"messages.shopedit-invalid-item");return;}ItemStack chosen=s.selected.clone();String id=chosen.getType().name().toLowerCase(Locale.ROOT)+"_"+slot;ShopItem old=c.getItemBySlot(slot);if(old!=null){id=old.id();p.getShopManager().removeConfigSection("categories."+c.id()+".items."+old.id());c.removeItem(old.id());}
  double price=parsePrice(chosen,p.getConfig().getDouble("shop-edit.default-price",100)); String display=chosen.hasItemMeta()&&chosen.getItemMeta().hasDisplayName()?chosen.getItemMeta().getDisplayName():"&f"+pretty(chosen.getType()); List<String> lore=chosen.hasItemMeta()&&chosen.getItemMeta().hasLore()?new ArrayList<>(chosen.getItemMeta().getLore()):new ArrayList<>(); if(p.getConfig().getBoolean("shop-edit.selection.strip-price-tags",false)){Pattern tag=Pattern.compile("\s*\[PRICE\]\s*[0-9]+(?:[.,][0-9]+)?",Pattern.CASE_INSENSITIVE);display=tag.matcher(display).replaceAll("").trim();lore.replaceAll(x->tag.matcher(x).replaceAll("").trim());lore.removeIf(String::isBlank);} ShopItem item=new ShopItem(id,chosen.getType(),display,lore,price,slot);c.addItem(item);String path="categories."+c.id()+".items."+id;p.getShopManager().setConfigValue(path+".material",item.material().name());p.getShopManager().setConfigValue(path+".name",item.displayName());p.getShopManager().setConfigValue(path+".lore",item.lore());p.getShopManager().setConfigValue(path+".buy",item.buyPrice());p.getShopManager().setConfigValue(path+".slot",item.slot());invRefresh(p,player,c);p.getLanguageManager().send(player,"messages.shopedit-item-saved");autosave(p);
 }
 private static double parsePrice(ItemStack i,double fallback){if(i.hasItemMeta()){ItemMeta m=i.getItemMeta();List<String> lines=new ArrayList<>();if(m.hasDisplayName())lines.add(m.getDisplayName());if(m.hasLore())lines.addAll(m.getLore());Pattern pat=Pattern.compile("\\[PRICE\\]\\s*([0-9]+(?:[.,][0-9]+)?)",Pattern.CASE_INSENSITIVE);for(String line:lines){Matcher x=pat.matcher(ChatColor.stripColor(line));if(x.find())try{double v=Double.parseDouble(x.group(1).replace(',','.'));if(Double.isFinite(v)&&v>0)return v;}catch(NumberFormatException ignored){}}}return fallback;}
 private static void invRefresh(DonutShop p,Player player,ShopCategory c){Inventory inv=player.getOpenInventory().getTopInventory();for(int i=9;i<inv.getSize();i++)inv.setItem(i,null);for(ShopItem item:c.items())if(item.slot()<inv.getSize())inv.setItem(item.slot(),ShopMenu.display(p,item));inv.setItem(4,help(p));}
 private static ItemStack help(DonutShop p){ItemStack i=new ItemStack(Material.KNOWLEDGE_BOOK);ItemMeta m=i.getItemMeta();m.setDisplayName(color(p.getConfig().getString("shop-edit.help.title","&bShopEdit Help")));m.setLore(List.of(color(p.getConfig().getString("shop-edit.help.select","&7Click an item in your inventory to select it.")),color(p.getConfig().getString("shop-edit.help.place","&7Left-click a shop slot to place it.")),color(p.getConfig().getString("shop-edit.help.remove","&7Right-click a shop slot to remove it.")),color("&7[PRICE] 250")));i.setItemMeta(m);return i;}
 private static String pretty(Material m){return Arrays.stream(m.name().toLowerCase(Locale.ROOT).split("_")).map(x->Character.toUpperCase(x.charAt(0))+x.substring(1)).reduce((a,b)->a+" "+b).orElse(m.name());}
 private static void autosave(DonutShop p){if(p.getConfig().getBoolean("shop-edit.auto-save",true))p.getShopManager().save();}
 public static void close(Player p){sessions.remove(p.getUniqueId());}
 private static int normalize(int n){if(n<27)n=27;if(n>54)n=54;return n-n%9;}
 private static String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}
}
